### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by poVoq** [AntonC9018/hopper-godot#2]
On Manjaro Linux here, but I can't get it to work.

First I seem to have this issue: https://github.com/godotengine/godot/issues/35897

But even after finding a likely fix for that, I still get a huge amount of errors in the console. Seems to be related to missing "Newtonsoft.Json" files. Not sure how to solve that one.

**Comment by AntonC9018** [comment]
Does removing nested .csproj files help?
```
cd Hopper
rm */*.csproj
```

**Comment by poVoq** [comment]
There is only `Hopper_Godot.csproj`

**Comment by AntonC9018** [comment]
Did you clone the nested hopper.cs repo, as specified in the readme? That repo contains a couple of .csproj files, which may interfere with the godot build process.

**Comment by poVoq** [comment]
I did not *hust*

Seems to work now.
